# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 
  "
  الحساب الصحيح من بنيان الحكم الرشيد
  <br>
  <small>
  تأليف:
  <br>
  ابن يوسف زكريا الطرابلسي
  </small>
  "
copyright: "2025"
author: "ابن يوسف زكريا الطرابلسي"
announcement: "هذا البحث لا يزال قيد الإجراء"
# logo: logo.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)


parse:
  myst_enable_extensions:
    - attrs_block
      # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  use_multitoc_numbering: true
  section_numbers: true
  home_page_in_navbar: false
  # secondary_sidebar_items: ["page-toc"]
  extra_css: "custom.css"
  extra_footer: "footer.html"
  extra_navbar: |
        <h1>
            your html Zakariya
        </h1>
  extra_footer: |
    <p>
    ... Add license info here...
    </p>
sphinx:
  config:
    language: ar
    # html_baseurl: 'https://dipranjan.github.io/dsinterviewqns/'
    html_show_copyright: false
  extra_extensions:
    # - attrs_block
    # - sphinx_sitemap
  latex_elements:
    preamble: r'\usepackage{quran}'
    
