name: Build Website

# Controls when the workflow will run
on: 
  # [push, pull_request, workflow_dispatch]
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main

# permissions:
#   contents: write

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.11.9
        uses: actions/setup-python@v2
        with:
           python-version: "3.11.9"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Installation Process has started.
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f quran
